### ISSUE TITLE
Simple build throws an error

### ISSUE THREAD

**Issue by sven-s** [MartinJohns/DatedTodo#1]
I created a console application in c# and added the nuget package. When building it directly I get the following error: 

Error   

1   The command "..\packages\DatedTodo.0.1.1.0\tools\DatedTodo.exe "C:\Users\sven\dev\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.csproj"" exited with code -532462766. ConsoleApplication1

**Comment by MartinJohns** [comment]
This package requires .net 4.5 to be installed on the machine. Is this the case?

Please also check the output window for additional error messages.

**Comment by sven-s** [comment]
Sorry, I forgot to provide environment info:

Windows 10 Tech Preview
Visual Studio 2013 Pro Update 4
.NET 4.51

I've tried it with 4.5 and 4.51 => both failed.

**Comment by sven-s** [comment]
Here is the build output:

1>------ Build started: Project: ConsoleApplication1, Configuration: Debug Any CPU ------
1>  
1>  Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
1>     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
1>     at System.Reflection.RuntimeAssembly.get_DefinedTypes()
1>     at System.Composition.Hosting.ContainerConfiguration.<WithAssemblies>b__0(Assembly a)
1>     at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
1>     at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
1>     at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
1>     at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
1>     at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.CreateMefHostServices()
1>     at DatedTodo.Program.<MainAsync>d__1.MoveNext()
1>     --- End of inner exception stack trace ---
1>     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
1>     at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
1>     at DatedTodo.Program.Main(String[] args)
1>C:\Users\sven\dev\ConsoleApplication1\packages\DatedTodo.0.1.1.0\build\DatedTodo.targets(4,5): error MSB3073: The command "..\packages\DatedTodo.0.1.1.0\tools\DatedTodo.exe "C:\Users\sven\dev\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.csproj"" exited with code 255.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by MartinJohns** [comment]
I tested it on Windows 10 Technical Preview and Windows 8.1 Pro, with VS2013 and VS2015. But on both machines I had VS2015 installed. I suspect this is not the case with you and some dependencies are missing. I'll check this tomorrow morning.

**Comment by sven-s** [comment]
I will install VS 2015 as well on my machine and will report if that fix it.

**Comment by sven-s** [comment]
I installed Visual Studio 2015. Now it's building! Do you know how to make run without VS 2015? Or what could the missing dependency be?

**Comment by MartinJohns** [comment]
I don't know what could be missing. Tomorrow I'll add some debug information and spin up a VM to see what's missing.

**Comment by sven-s** [comment]
Could this be a fix: http://stackoverflow.com/questions/27831293/what-parts-of-roslyn-can-you-use-with-vs-2013

**Comment by MartinJohns** [comment]
Apparently you need to have the MSBuild 14 tools installed in order to use `OpenSolution/ProjectAsync` with Roslyn. I'm not sure whether I'm allowed to distribute the assemblies with the application.

Might be better to rewrite the program to parse the comments without Roslyn. This will also make it easier to support machines running only .NET 4.0.

**Comment by MartinJohns** [comment]
Sorry that it took so long, I barely found the time for this.

I removed the usage of Roslyn and parsed the complete source manually using a regular expression. This is more error prone as it will also catch TODO-items in strings. But in return the application is much smaller and faster (~50ms instead of 2s in my test project) and has no dependencies. This also allowed me to switch to .NET 4.0, making it possible to use this tooling on machines that do not yet have the .NET 4.5 support (some people are this unfortunate).
